[tool.poetry]
name = "flightscope"
version = "0.1.0"
description = "Interactive flight simulator/real time inspector app"
authors = ["Nazenano", "Fakas"]
readme = "README.md"
homepage = "https://github.com/Nazenano/flightscope"

[tool.poetry.dependencies]
python = ">=3.13"
numpy = "^2.3.3"
black = "^25.9.0"
pygame = "^2.6.1"
pyopengl = "^3.1.10"
pyopengl-accelerate = "^3.1.10"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
